version: '3.1'
services:

  fusers:
    build: 
      dockerfile: docker/fusers/Dockerfile
      context: ./
    image: fusers-crud
    command: ["python", "main.py"]
    volumes:
      - ./fusers-crud/:/opt/app/
    ports:
      - 5000:5000
    env_file:
      - .env

  mysql-fcuj:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - 3306:3306
    volumes:
      - mysql-fcuj:/var/lib/mysql

  adminer-fcuj:
    image: adminer
    ports:
        - "8080:8080"

volumes:
  mysql-fcuj: